---
- name: Play - Install and configure Nginx as a LoadBalancer
  hosts: localhost
  become: yes
  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy the Nginx config file to /etc/nginx/sites-available
      copy:
        src: path/to/nginx.conf
        dest: /etc/nginx/sites-available/nginx.conf
      become: yes

    - name: Create symlink of the config file at /etc/nginx/sites-enabled
      file:
        src: /etc/nginx/sites-available/nginx.conf
        dest: /etc/nginx/sites-enabled/nginx.conf
        state: link
      become: yes

    - name: Restart nginx to apply changes
      service:
        name: nginx
        state: restarted
